before_script:
  - 'dotnet restore --verbosity n'

stages:
  - build
  - test
  - documentation

build:
  stage: build
  script:
    - .\BuildProject.cmd
  except:
    - tags

copyright:
  stage: test
  script:
    .\CheckCopyrightAllFiles.cmd
  except:
    - tags

lint:
  stage: test
  script:
    - .\RunResharper.cmd
  except:
    - tags

test:
  stage: test
  script:
    - .\TestProject.cmd
  except:
    - tags

update_documentation:
  stage: documentation
  script:
    - .\UploadDocumentation.cmd
  except:
    - tags
