variables:
  Solution: MySolution.sln

before_script:
  - 'dotnet restore'

stages:
  - build
  - test

build:
  stage: build
  script:
  - echo building...
  - 'dotnet build "Thesis - Multicut in Trees"'
  except:
  - tags

test:
  stage: test
  script:
  - echo testing...
  - 'dotnet test "TESTS - Multicut in Trees" /p:CollectCoverage=true'
  except:
  - tags
