before_script:
  - 'dotnet restore'

stages:
  - build
  - test

build:
  stage: build
  script:
    - .\BuildProject.cmd
  except:
    - tags

copyright:
  stage: test
  script:
    .\CheckCopyrightAllFiles.cmd
  except:
    - tags

lint:
  stage: test
  script:
    - .\RunResharper.cmd
  except:
    - tags

test:
  stage: test
  script:
    - .\TestProject.cmd
  except:
    - tags
