before_script:
  - 'dotnet restore'

stages:
  - build
  - test
  - documentation

build:
  stage: build
  script:
    - .\BuildProject.cmd
  except:
    - tags

copyright:
  stage: test
  script:
    .\CheckCopyrightAllFiles.cmd
  except:
    - tags

lint:
  stage: test
  script:
    - .\RunResharper.cmd
  except:
    - tags

test:
  stage: test
  script:
    - .\TestProject.cmd
  except:
    - tags

update_documentation:
  stage: documentation
  script:
    - git remote set-url origin https://s.a.heinen:${CI_PUSH_TOKEN}@git.science.uu.nl/s.a.heinen/thesis-multicut-in-trees.wiki.git
    - git config --global user.email 's.a.heinen@uu.nl'
    - git config --global user.name 'Heinen,S.A. (Steven)'
    - .\UploadDocumentation.cmd
  except:
    - tags
