title Linter
echo Inspecting code...
jb inspectcode "Thesis - Multicut in Trees.sln" -o=".\Resharper\inspectcode.xml"
echo Running cleanup...
jb cleanupcode "Thesis - Multicut in Trees.sln"
echo Detecting duplicates...
jb dupfinder "Thesis - Multicut in Trees.sln" -o=".\Resharper\dupfinder.xml"
pause