echo Inspecting code...
C:\Users\steve\.dotnet\tools\jb inspectcode "MulticutInTrees\MulticutInTrees.csproj" -o=".\Resharper\inspectcode.xml"
echo Detecting duplicates...
C:\Users\steve\.dotnet\tools\jb dupfinder "MulticutInTrees\MulticutInTrees.csproj" -o=".\Resharper\dupfinder.xml"