REM This file will use Guo and Niedermeier's kernelisation algorithm to solve instances.
REM Trees are generated using the Prüfer method, and demand pairs are generated uniform randomly.
REM The used numbers of nodes are: 128, 256, 384, 512, 640, 768, 896, 1024.
REM The used numbers of demand pairs are: 128, 256, 384, 512, 640, 768, 896, 1024.
REM There are 10 different instances for each combination of nodes and demand pair.
REM This means the seeds for the RNG are: 0, 1, ..., 9.
REM Each instance will be repeated 10 times to compensate for difference in running time because of external factors.
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=128 --nrDPs=128
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=128 --nrDPs=256
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=128 --nrDPs=384
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=128 --nrDPs=512
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=128 --nrDPs=640
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=128 --nrDPs=768
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=128 --nrDPs=896
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=128 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=256 --nrDPs=128
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=256 --nrDPs=256
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=256 --nrDPs=384
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=256 --nrDPs=512
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=256 --nrDPs=640
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=256 --nrDPs=768
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=256 --nrDPs=896
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=256 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=384 --nrDPs=128
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=384 --nrDPs=256
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=384 --nrDPs=384
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=384 --nrDPs=512
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=384 --nrDPs=640
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=384 --nrDPs=768
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=384 --nrDPs=896
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=384 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=512 --nrDPs=128
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=512 --nrDPs=256
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=512 --nrDPs=384
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=512 --nrDPs=512
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=512 --nrDPs=640
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=512 --nrDPs=768
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=512 --nrDPs=896
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=512 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=640 --nrDPs=128
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=640 --nrDPs=256
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=640 --nrDPs=384
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=640 --nrDPs=512
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=640 --nrDPs=640
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=640 --nrDPs=768
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=640 --nrDPs=896
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=640 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=768 --nrDPs=128
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=768 --nrDPs=256
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=768 --nrDPs=384
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=768 --nrDPs=512
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=768 --nrDPs=640
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=768 --nrDPs=768
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=768 --nrDPs=896
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=768 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=896 --nrDPs=128
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=896 --nrDPs=256
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=896 --nrDPs=384
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=896 --nrDPs=512
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=896 --nrDPs=640
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=896 --nrDPs=768
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=896 --nrDPs=896
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=896 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=1024 --nrDPs=128
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=1024 --nrDPs=256
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=1024 --nrDPs=384
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=1024 --nrDPs=512
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=1024 --nrDPs=640
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=1024 --nrDPs=768
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=1024 --nrDPs=896
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierPruferRandomSmall" -v --nrNodes=1024 --nrDPs=1024
pause