REM This file will use Guo and Niedermeier's kernelisation algorithm to solve instances.
REM Trees are generated using the Prüfer method, and demand pairs are generated uniform randomly.
REM The used numbers of nodes are: 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072.
REM The used numbers of demand pairs are: 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536.
REM There are 10 different instances for each combination of nodes and demand pair.
REM This means the seeds for the RNG are: 0, 1, ..., 9.
REM Each instance will be repeated 10 times to compensate for difference in running time because of external factors.
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=8192 --nrDPs=128
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=8192 --nrDPs=256
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=8192 --nrDPs=512
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=8192 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=8192 --nrDPs=2048
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=8192 --nrDPs=4096
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=8192 --nrDPs=8192
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=8192 --nrDPs=16384
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=8192 --nrDPs=32768
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=8192 --nrDPs=65536
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=16384 --nrDPs=128
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=16384 --nrDPs=256
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=16384 --nrDPs=512
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=16384 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=16384 --nrDPs=2048
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=16384 --nrDPs=4096
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=16384 --nrDPs=8192
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=16384 --nrDPs=16384
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=16384 --nrDPs=32768
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=16384 --nrDPs=65536
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=32768 --nrDPs=128
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=32768 --nrDPs=256
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=32768 --nrDPs=512
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=32768 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=32768 --nrDPs=2048
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=32768 --nrDPs=4096
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=32768 --nrDPs=8192
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=32768 --nrDPs=16384
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=32768 --nrDPs=32768
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=32768 --nrDPs=65536
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=65536 --nrDPs=128
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=65536 --nrDPs=256
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=65536 --nrDPs=512
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=65536 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=65536 --nrDPs=2048
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=65536 --nrDPs=4096
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=65536 --nrDPs=8192
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=65536 --nrDPs=16384
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=65536 --nrDPs=32768
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=65536 --nrDPs=65536
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=131072 --nrDPs=128
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=131072 --nrDPs=256
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=131072 --nrDPs=512
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=131072 --nrDPs=1024
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=131072 --nrDPs=2048
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=131072 --nrDPs=4096
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=131072 --nrDPs=8192
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=131072 --nrDPs=16384
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=131072 --nrDPs=32768
..\MulticutInTrees\bin\Experiment\netcoreapp3.1\MulticutInTrees.exe --seed=0 --experiments=10 --repetitions=10 --algorithm=GuoNiedermeierKernelisation --treeType=Prufer --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=131072 --nrDPs=65536
pause