REM This file will use Guo and Niedermeier's kernelisation algorithm to solve instances.
REM Trees are generated using the Caterpillar method, and demand pairs are generated uniform randomly.
REM The used numbers of nodes are: 2048, 3072, 4096, 5120, 6144, 7168, 8192, 9216, 10240.
REM The used numbers of demand pairs are: 2048, 3072, 4096, 5120, 6144, 7168, 8192, 9216, 10240.
REM There are 5 different instances for each combination of nodes and demand pair.
REM Each instance will be repeated 5 times to compensate for difference in running time because of external factors.
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=5650002 --dpSeed=8742529 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=8192 --nrDPs=8192
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=5173460 --dpSeed=6303822 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=8192 --nrDPs=9216
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=6430090 --dpSeed=8815400 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=8192 --nrDPs=10240
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=8509602 --dpSeed=1664007 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=9216 --nrDPs=2048
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=5625488 --dpSeed=2925260 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=9216 --nrDPs=3072
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=8784420 --dpSeed=4970324 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=9216 --nrDPs=4096
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=7741651 --dpSeed=4349644 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=9216 --nrDPs=5120
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=3041621 --dpSeed=4375012 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=9216 --nrDPs=6144
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=4484437 --dpSeed=2650886 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=9216 --nrDPs=7168
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=1690760 --dpSeed=999724 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=9216 --nrDPs=8192
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=1344404 --dpSeed=1556336 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=9216 --nrDPs=9216
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=7703744 --dpSeed=3819503 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=9216 --nrDPs=10240
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=6321160 --dpSeed=2056949 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=10240 --nrDPs=2048
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=4278543 --dpSeed=2046464 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=10240 --nrDPs=3072
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=6719757 --dpSeed=8560893 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=10240 --nrDPs=4096
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=4941706 --dpSeed=7466655 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=10240 --nrDPs=5120
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=5026283 --dpSeed=2867150 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=10240 --nrDPs=6144
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=2007081 --dpSeed=7351151 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=10240 --nrDPs=7168
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=6144137 --dpSeed=805434 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=10240 --nrDPs=8192
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=3743791 --dpSeed=7328178 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=10240 --nrDPs=9216
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=2355971 --dpSeed=2035969 --experiments=50 --repetitions=1 --algorithm=GuoNiedermeierKernelisation --treeType=Caterpillar --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\GuoNiedermeierCaterpillarRandomLarge" -v --nrNodes=10240 --nrDPs=10240
pause