REM This file will use the Gurobi MIP solver to compute ideal K values for a number of experiments.
REM Trees are generated using the Degree3 tree method, and demand pairs are generated uniform randomly.
REM The used numbers of nodes are: 2048, 3072, 4096, 5120, 6144, 7168, 8192, 9216, 10240.
REM The used numbers of demand pairs are: 2048, 3072, 4096, 5120, 6144, 7168, 8192, 9216, 10240.
REM There are 5 different instances for each combination of nodes and demand pair.
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=552994 --dpSeed=161165 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=10240 --nrDPs=8192 --maxSolutionSize=0
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=1482884 --dpSeed=5824609 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=10240 --nrDPs=9216 --maxSolutionSize=0

for /r D:\Documents\Universiteit\Thesis\GNPVertexCoverInstances\ %%i in (*.mis) do (
..\..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --algorithm=BousquetKernelisation --treeType=VertexCover --dpType=FromTreeInstance --instanceDir="D:\Documents\Universiteit\Thesis\Instances\GNPVertexCover-instances" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults\BousquetGNPVertexCover" -v --instanceFilePath="%%i"
)

..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=4043487 --dpSeed=1588423 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=10240 --nrDPs=10240 --maxSolutionSize=0
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=7038828 --dpSeed=9029570 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=9216 --nrDPs=2048 --maxSolutionSize=0
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=2489585 --dpSeed=8303415 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=9216 --nrDPs=3072 --maxSolutionSize=0
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=7731575 --dpSeed=5796218 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=9216 --nrDPs=4096 --maxSolutionSize=0
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=8902733 --dpSeed=3177040 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=9216 --nrDPs=5120 --maxSolutionSize=0
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=1650353 --dpSeed=3832721 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=9216 --nrDPs=6144 --maxSolutionSize=0
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=8749259 --dpSeed=6078828 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=9216 --nrDPs=7168 --maxSolutionSize=0
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=4899732 --dpSeed=1705491 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=9216 --nrDPs=8192 --maxSolutionSize=0
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=1077544 --dpSeed=7202262 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=9216 --nrDPs=9216 --maxSolutionSize=0
..\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe --treeSeed=3354898 --dpSeed=9281276 --experiments=50 --repetitions=1 --algorithm=GenerateInstances --treeType=Degree3Tree --dpType=Random --instanceDir="D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomLarge" --outputDir="D:\Documents\Universiteit\Thesis\ExperimentResults" -v --nrNodes=9216 --nrDPs=10240 --maxSolutionSize=0
del mipMinSolSizeSolver.log
pause
