set "exeLocation=P:\Thesis - Multicut in Trees\MulticutInTrees\bin\Experiment\net5.0\MulticutInTrees.exe"
set "experiments=100"
set "repetitions=1"
set "algorithm=GenerateInstances"
set "multicutInstanceDir=D:\Documents\Universiteit\Thesis\Instances\Degree3TreeRandomSmall"
set "resultsOutputDir=D:\Documents\Universiteit\Thesis\ExperimentResults"
"%exeLocation%" --treeSeed=5225706 --dpSeed=4656174 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=128 --nrDPs=128 --maxSolutionSize=0
"%exeLocation%" --treeSeed=8173074 --dpSeed=8246651 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=128 --nrDPs=256 --maxSolutionSize=0
"%exeLocation%" --treeSeed=3744801 --dpSeed=6560504 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=128 --nrDPs=384 --maxSolutionSize=0
"%exeLocation%" --treeSeed=9485364 --dpSeed=2937060 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=128 --nrDPs=512 --maxSolutionSize=0
"%exeLocation%" --treeSeed=8538786 --dpSeed=5258418 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=128 --nrDPs=640 --maxSolutionSize=0
"%exeLocation%" --treeSeed=5892964 --dpSeed=1560270 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=128 --nrDPs=768 --maxSolutionSize=0
"%exeLocation%" --treeSeed=3602467 --dpSeed=8470493 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=128 --nrDPs=896 --maxSolutionSize=0
"%exeLocation%" --treeSeed=5554598 --dpSeed=4495940 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=128 --nrDPs=1024 --maxSolutionSize=0
"%exeLocation%" --treeSeed=8309237 --dpSeed=6848809 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=256 --nrDPs=128 --maxSolutionSize=0
"%exeLocation%" --treeSeed=2664712 --dpSeed=4684575 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=256 --nrDPs=256 --maxSolutionSize=0
"%exeLocation%" --treeSeed=5517752 --dpSeed=571130 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=256 --nrDPs=384 --maxSolutionSize=0
"%exeLocation%" --treeSeed=6700518 --dpSeed=5392545 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=256 --nrDPs=512 --maxSolutionSize=0
"%exeLocation%" --treeSeed=7253332 --dpSeed=2579618 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=256 --nrDPs=640 --maxSolutionSize=0
"%exeLocation%" --treeSeed=2702190 --dpSeed=5747842 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=256 --nrDPs=768 --maxSolutionSize=0
"%exeLocation%" --treeSeed=8958544 --dpSeed=7658822 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=256 --nrDPs=896 --maxSolutionSize=0
"%exeLocation%" --treeSeed=1011611 --dpSeed=5404309 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=256 --nrDPs=1024 --maxSolutionSize=0
"%exeLocation%" --treeSeed=8362051 --dpSeed=5689673 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=384 --nrDPs=128 --maxSolutionSize=0
"%exeLocation%" --treeSeed=6640166 --dpSeed=7185719 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=384 --nrDPs=256 --maxSolutionSize=0
"%exeLocation%" --treeSeed=3652824 --dpSeed=9981842 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=384 --nrDPs=384 --maxSolutionSize=0
"%exeLocation%" --treeSeed=6269209 --dpSeed=7451267 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=384 --nrDPs=512 --maxSolutionSize=0
"%exeLocation%" --treeSeed=6327359 --dpSeed=8525263 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=384 --nrDPs=640 --maxSolutionSize=0
"%exeLocation%" --treeSeed=9533447 --dpSeed=9418663 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=384 --nrDPs=768 --maxSolutionSize=0
"%exeLocation%" --treeSeed=1483188 --dpSeed=9208743 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=384 --nrDPs=896 --maxSolutionSize=0
"%exeLocation%" --treeSeed=2277928 --dpSeed=2908933 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=384 --nrDPs=1024 --maxSolutionSize=0
"%exeLocation%" --treeSeed=7995586 --dpSeed=3996449 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=512 --nrDPs=128 --maxSolutionSize=0
"%exeLocation%" --treeSeed=7502856 --dpSeed=4036902 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=512 --nrDPs=256 --maxSolutionSize=0
"%exeLocation%" --treeSeed=9792935 --dpSeed=9709877 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=512 --nrDPs=384 --maxSolutionSize=0
"%exeLocation%" --treeSeed=7904551 --dpSeed=7852552 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=512 --nrDPs=512 --maxSolutionSize=0
"%exeLocation%" --treeSeed=3852360 --dpSeed=8416486 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=512 --nrDPs=640 --maxSolutionSize=0
"%exeLocation%" --treeSeed=9357274 --dpSeed=820864 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=512 --nrDPs=768 --maxSolutionSize=0
"%exeLocation%" --treeSeed=8110790 --dpSeed=8156602 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=512 --nrDPs=896 --maxSolutionSize=0
"%exeLocation%" --treeSeed=5098864 --dpSeed=6062382 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=512 --nrDPs=1024 --maxSolutionSize=0
"%exeLocation%" --treeSeed=9270675 --dpSeed=3545328 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=640 --nrDPs=128 --maxSolutionSize=0
"%exeLocation%" --treeSeed=5405328 --dpSeed=1387283 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=640 --nrDPs=256 --maxSolutionSize=0
"%exeLocation%" --treeSeed=624839 --dpSeed=557131 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=640 --nrDPs=384 --maxSolutionSize=0
"%exeLocation%" --treeSeed=9796148 --dpSeed=5105367 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=640 --nrDPs=512 --maxSolutionSize=0
"%exeLocation%" --treeSeed=6626475 --dpSeed=5124378 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=640 --nrDPs=640 --maxSolutionSize=0
"%exeLocation%" --treeSeed=6273318 --dpSeed=9717351 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=640 --nrDPs=768 --maxSolutionSize=0
"%exeLocation%" --treeSeed=5624193 --dpSeed=5695198 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=640 --nrDPs=896 --maxSolutionSize=0
"%exeLocation%" --treeSeed=9207923 --dpSeed=3404493 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=640 --nrDPs=1024 --maxSolutionSize=0
"%exeLocation%" --treeSeed=9739330 --dpSeed=339018 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=768 --nrDPs=128 --maxSolutionSize=0
"%exeLocation%" --treeSeed=2879229 --dpSeed=9321970 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=768 --nrDPs=256 --maxSolutionSize=0
"%exeLocation%" --treeSeed=4971697 --dpSeed=6276444 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=768 --nrDPs=384 --maxSolutionSize=0
"%exeLocation%" --treeSeed=5891568 --dpSeed=6672409 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=768 --nrDPs=512 --maxSolutionSize=0
"%exeLocation%" --treeSeed=2844807 --dpSeed=3059618 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=768 --nrDPs=640 --maxSolutionSize=0
"%exeLocation%" --treeSeed=7268366 --dpSeed=2063195 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=768 --nrDPs=768 --maxSolutionSize=0
"%exeLocation%" --treeSeed=8145530 --dpSeed=5451953 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=768 --nrDPs=896 --maxSolutionSize=0
"%exeLocation%" --treeSeed=2982192 --dpSeed=5878045 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=768 --nrDPs=1024 --maxSolutionSize=0
"%exeLocation%" --treeSeed=9886311 --dpSeed=7425915 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=896 --nrDPs=128 --maxSolutionSize=0
"%exeLocation%" --treeSeed=4153052 --dpSeed=3210603 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=896 --nrDPs=256 --maxSolutionSize=0
"%exeLocation%" --treeSeed=6236655 --dpSeed=6611097 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=896 --nrDPs=384 --maxSolutionSize=0
"%exeLocation%" --treeSeed=1070332 --dpSeed=9490771 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=896 --nrDPs=512 --maxSolutionSize=0
"%exeLocation%" --treeSeed=291179 --dpSeed=1183754 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=896 --nrDPs=640 --maxSolutionSize=0
"%exeLocation%" --treeSeed=4395589 --dpSeed=7820113 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=896 --nrDPs=768 --maxSolutionSize=0
"%exeLocation%" --treeSeed=3188598 --dpSeed=7060593 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=896 --nrDPs=896 --maxSolutionSize=0
"%exeLocation%" --treeSeed=6120569 --dpSeed=4870526 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=896 --nrDPs=1024 --maxSolutionSize=0
"%exeLocation%" --treeSeed=174460 --dpSeed=9327382 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=1024 --nrDPs=128 --maxSolutionSize=0
"%exeLocation%" --treeSeed=4481695 --dpSeed=2959845 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=1024 --nrDPs=256 --maxSolutionSize=0
"%exeLocation%" --treeSeed=7320900 --dpSeed=4699902 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=1024 --nrDPs=384 --maxSolutionSize=0
"%exeLocation%" --treeSeed=2077314 --dpSeed=4990261 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=1024 --nrDPs=512 --maxSolutionSize=0
"%exeLocation%" --treeSeed=3099046 --dpSeed=901469 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=1024 --nrDPs=640 --maxSolutionSize=0
"%exeLocation%" --treeSeed=7877230 --dpSeed=2188157 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=1024 --nrDPs=768 --maxSolutionSize=0
"%exeLocation%" --treeSeed=3681782 --dpSeed=3602442 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=1024 --nrDPs=896 --maxSolutionSize=0
"%exeLocation%" --treeSeed=5903989 --dpSeed=9670436 --experiments="%experiments%" --repetitions="%repetitions%" --algorithm="%algorithm%" --treeType=Degree3Tree --dpType=Random --instanceDir="%multicutInstanceDir%" --outputDir="%resultsOutputDir%" -v --nrNodes=1024 --nrDPs=1024 --maxSolutionSize=0
del mipMinSolSizeSolver.log
